name-template: '$RESOLVED_VERSION'
tag-template: '$RESOLVED_VERSION'
categories:
- title: 'Features'
  labels:
    - 'feature'
    - 'enhancement'
- title: 'Bug Fixes'
  labels:
    - 'fix'
    - 'bugfix'
    - 'bug'
- title: 'Maintenance'
  label: 'chore'
version-resolver:
  major:
    labels:
      - 'bump-major'
  minor:
    labels:
      - 'bump-minor'
  patch:
    labels:
      - 'bump-patch'
  default: patch
template: |
  $CHANGES
