services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/postgres
      - PORT=8080
    env_file:
      - .env.docker
  db:
    image: postgres:latest@sha256:a9abf4275f9e99bff8e6aed712b3b7dfec9cac1341bba01c1ffdfce9ff9fc34a
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
