services:
  web:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/postgres
      - PORT=8080
    env_file:
      - .env.docker
  db:
    image: postgres:latest@sha256:3a82e1f56c8f0f5616a11103ac3d47e632c3938698946a7ad26da0df1334744a
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
