name: actionlint

on:
  push:

jobs:
  actionlint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Download actionlint
        id: get_actionlint
        run: bash <(curl https://raw.githubusercontent.com/rhysd/actionlint/main/scripts/download-actionlint.bash) 1.7.12
        shell: bash
      - name: Check workflow files
        env:
          ACTIONLINT: ${{ steps.get_actionlint.outputs.executable }}
        run: $ACTIONLINT -color
        shell: bash
