name: Release Drafter

on:
  push:
    branches:
      - main

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: release-drafter/release-drafter@4d75298e00d9e34c483e5ff8c68d0ea1c1940c1e # v7.5.1
        id: release_drafter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: taiki-e/install-action@2ca9b94c269419b7b0c711c09d0b21c4e1d51145 # v2.83.1
        with:
          tool: cargo-edit
      - name: Update Cargo.toml
        env:
          TAG_NAME: ${{ steps.release_drafter.outputs.tag_name }}
        run: |
          cargo set-version "${TAG_NAME}"
        continue-on-error: true
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8.1.1
        with:
          commit-message: Bump version to ${{ steps.release_drafter.outputs.tag_name }}
          branch: chore/bump-version
          title: "chore: bump version to ${{ steps.release_drafter.outputs.tag_name }}"
          body: |
            Automated version bump from Release Drafter
