name: Release Drafter

on:
  push:
    branches:
      - main

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: release-drafter/release-drafter@v5
        id: release_drafter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: taiki-e/install-action@v2
        with:
          tool: cargo-edit
      - name: Update Cargo.toml
        run: |
          cargo set-version ${{ steps.release_drafter.outputs.tag_name }}
        continue-on-error: true
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Bump version

