name: zizmor

on: [push]

jobs:
  zizmor:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Install zizmor
        run: pip install zizmor==1.23.1
      - name: Run zizmor
        run: zizmor .
